//! Offline generator for the vendored CLDR country -> language table.
//! Run via `cargo run -p locale-gen`. NOT published.

use serde_json::Value;

/// One emitted table row: an uppercase country code and its ranked language
/// subtags (dominant first).
#[derive(Debug, PartialEq, Eq)]
pub struct CountryRow {
    pub cc: String,
    pub langs: Vec<String>,
}

/// Keep a language if it is official-ish OR spoken by at least this percent.
const POP_THRESHOLD: f64 = 20.0;

/// Transform CLDR `territoryInfo` JSON into sorted, ranked rows.
pub fn rows_from_cldr(v: &Value) -> Vec<CountryRow> {
    let mut rows = Vec::new();
    let Some(map) = v["supplemental"]["territoryInfo"].as_object() else {
        return rows;
    };
    for (cc, info) in map {
        if cc.len() != 2 || !cc.bytes().all(|b| b.is_ascii_alphabetic()) {
            continue; // skip "001" etc.
        }
        let Some(lp) = info.get("languagePopulation").and_then(Value::as_object) else {
            continue;
        };
        let mut langs: Vec<(String, f64, bool)> = lp
            .iter()
            .filter_map(|(lang, d)| {
                let pop = d
                    .get("_populationPercent")
                    .and_then(Value::as_str)
                    .and_then(|s| s.parse::<f64>().ok())
                    .unwrap_or(0.0);
                let official = d
                    .get("_officialStatus")
                    .and_then(Value::as_str)
                    .is_some_and(|s| s.starts_with("official") || s == "de_facto_official");
                if official || pop >= POP_THRESHOLD {
                    let subtag = lang.split('_').next().unwrap_or(lang).to_lowercase();
                    Some((subtag, pop, official))
                } else {
                    None
                }
            })
            .collect();
        langs.sort_by(|a, b| {
            b.2.cmp(&a.2)
                .then(b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal))
        });
        let mut seen = std::collections::HashSet::new();
        let ranked: Vec<String> = langs
            .into_iter()
            .map(|(s, _, _)| s)
            .filter(|s| seen.insert(s.clone()))
            .collect();
        if !ranked.is_empty() {
            rows.push(CountryRow {
                cc: cc.to_uppercase(),
                langs: ranked,
            });
        }
    }
    rows.sort_by(|a, b| a.cc.cmp(&b.cc));
    rows
}

/// Emit the `table.rs` source for the stealth crate.
pub fn emit_rust(version: &str, rows: &[CountryRow]) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "// CLDR {version}. Generated by `cargo run -p locale-gen`. DO NOT EDIT.\n"
    ));
    s.push_str(&format!(
        "pub(crate) static CLDR_VERSION: &str = \"{version}\";\n\n"
    ));
    s.push_str("/// Sorted by country code (binary-searchable). Ranked language subtags, dominant first.\n");
    s.push_str("pub(crate) static COUNTRIES: &[(&str, &[&str])] = &[\n");
    for r in rows {
        let langs = r
            .langs
            .iter()
            .map(|l| format!("\"{l}\""))
            .collect::<Vec<_>>()
            .join(", ");
        s.push_str(&format!("    (\"{}\", &[{}]),\n", r.cc, langs));
    }
    s.push_str("];\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> Value {
        serde_json::from_str(include_str!("../tests/fixtures/territoryInfo-mini.json")).unwrap()
    }

    #[test]
    fn rows_skip_world_region_and_rank() {
        let rows = rows_from_cldr(&fixture());
        let ccs: Vec<&str> = rows.iter().map(|r| r.cc.as_str()).collect();
        assert_eq!(ccs, vec!["CH", "US"]); // sorted, "001" skipped
        let us = rows.iter().find(|r| r.cc == "US").unwrap();
        assert_eq!(us.langs, vec!["en"]); // es below threshold (9.6 < 20, not official)
        let ch = rows.iter().find(|r| r.cc == "CH").unwrap();
        assert_eq!(ch.langs[0], "de"); // dominant official first
        assert!(ch.langs.contains(&"fr".to_string()));
        assert!(ch.langs.contains(&"it".to_string()));
    }

    #[test]
    fn emit_is_valid_rust_shape() {
        let rows = rows_from_cldr(&fixture());
        let out = emit_rust("46.0.0", &rows);
        assert!(out.contains("CLDR_VERSION: &str = \"46.0.0\""));
        assert!(out.contains("(\"US\", &[\"en\"]),"));
        assert!(out.contains("(\"CH\", &["));
    }
}
